services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: university_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: university_db
      MYSQL_USER: university_user
      MYSQL_PASSWORD: university_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - university_network
    command: --default-authentication-plugin=mysql_native_password

  # Aplicação Node.js
  app:
    build: .
    container_name: university_app
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: mysql
      DB_USER: university_user
      DB_PASSWORD: university_pass
      DB_NAME: university_db
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    networks:
      - university_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  mysql_data:

networks:
  university_network:
    driver: bridge
